[package]
name = "attomath"
version = "0.1.0"
authors = ["Matthias Deiml <matthias@deiml.net>"]
edition = "2018"

[features]
default = ['use-serde']

use-serde = ['serde']

[dependencies]
serde = {version = "1.0", features = ["derive"], optional = true}
